[package]
name = "juniper_rocket"
version = "0.4.1"
authors = [
    "Magnus Hallin <mhallin@fastmail.com>",
    "Christoph Herzog <chris@theduke.at>",
]
description = "Juniper GraphQL integration with Rocket"
license = "BSD-2-Clause"
documentation = "https://docs.rs/juniper_rocket"
repository = "https://github.com/graphql-rust/juniper"
edition = "2018"

[dependencies]
serde = { version = "1.0.2" }
serde_json = { version = "1.0.2" }
serde_derive = { version = "1.0.2" }
juniper = { version = "0.13.1" , default-features = false, path = "../juniper", features=["async"]}

# this is imported because rocket does not expose "tokio_io::AsyncReadExt" anymore
tokio-io = "=0.2.0-alpha.6"

# todo: cargo.toml from async-await

futures = { version = "0.3.0-alpha.19", package = "futures-preview", features = ["compat"] }
futures1 = { version = "0.1.29", package = "futures" }
rocket = { git = "https://github.com/SergioBenitez/Rocket", branch = "async" }

#[dev-dependencies.juniper]
#version = "0.13.1"
#features = ["expose-test-schema", "serde_json"]
#path = "../juniper"
