[package]
name = "juniper_warp"
version = "0.5.0"
authors = ["Tom Houlé <tom@tomhoule.com>"]
description = "Juniper GraphQL integration with Warp"
license = "BSD-2-Clause"
documentation = "https://docs.rs/juniper_warp"
repository = "https://github.com/graphql-rust/juniper"
edition = "2018"

[features]
async = [ "juniper/async", "futures03" ]

[dependencies]
#warp = "0.1.20"
warp = { git = "https://github.com/seanmonstar/warp.git" }
juniper = { version = "0.14.0", path = "../juniper", default-features = false  }
serde_json = "1.0.24"
serde_derive = "1.0.75"
failure = "0.1.2"
futures = "0.1.29"
serde = "1.0.75"
tokio-threadpool = "0.1.16"

futures03 = { version = "=0.3.0-alpha.19", optional = true, package = "futures-preview", features = ["compat"] }

[dev-dependencies]
juniper = { version = "0.14.0", path = "../juniper", features = ["expose-test-schema", "serde_json"] }
env_logger = "0.5.11"
log = "0.4.3"
percent-encoding = "1.0"
